### ISSUE TITLE
Plugin is now not compatible with KeePass (version 2.55)

### ISSUE THREAD

**Issue by KorneySan** [navossoc/KeePass-Yet-Another-Favicon-Downloader#78]
After KeePass update to version 2.55 I got its report about plugin incompatibility:

`[Window Title]
KeePass

[Content]
The following plugin is incompatible with the current KeePass version:
C:\Program Files\KeePass Password Safe 2\Plugins\YetAnotherFaviconDownloader.plgx

Have a look at the plugin's website for an appropriate version.

[Expanded Information]
A generic error occurred in GDI+.
System.Drawing
   at System.Drawing.Image.Save(Stream stream, ImageCodecInfo encoder, EncoderParameters encoderParams)
   at System.Drawing.Image.System.Runtime.Serialization.ISerializable.GetObjectData(SerializationInfo si, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)
   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
   at System.Resources.ResourceWriter.WriteValue(ResourceTypeCode typeCode, Object value, BinaryWriter writer, IFormatter objFormatter)
   at System.Resources.ResourceWriter.Generate()
   at KeePass.Plugins.PlgxPlugin.CompileEmbeddedRes(PlgxPluginInfo plgx)
   at KeePass.Plugins.PlgxPlugin.Compile(String strTmpRoot, PlgxPluginInfo plgx, String strBuildPre, String strBuildPost)
   at KeePass.Plugins.PlgxPlugin.ReadFile(BinaryReader br, PlgxPluginInfo plgx, IStatusLogger slStatus)
   at KeePass.Plugins.PlgxPlugin.LoadPriv(String strFilePath, IStatusLogger slStatus, Boolean bAllowCached, Boolean bAllowCompile, Boolean bAllowLoad, TextWriter twLog)
   at KeePass.Plugins.PlgxPlugin.Load(String strFilePath, IStatusLogger slStatus)
Void Save(System.IO.Stream, System.Drawing.Imaging.ImageCodecInfo, System.Drawing.Imaging.EncoderParameters)

[V] Details  [ОК]`

Please fix it ASAP.

P.S. With versions up to 2.54 all was ok.

**Comment by navossoc** [comment]
I have dropped KeePass for KeePassXC (because of my Yubikey), so I really don't know if it actually continues to work or not.

However, I downloaded KeePass v2.55 (portable)  and did a test here with the latest version of the plugin, it compiled and opened normally.

![image](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/assets/2457338/ec31b648-9d19-4183-8944-2dce6b23ddab)

Looking at your call stack is really weird that something like that is happening.

This version was released on 2023-10-12 and no one commented on this issue.
Are you sure it's not something specific to your installation? Try a clean install using the portable version.

**Comment by KorneySan** [comment]
I had installed it at another computer and it works.
The only difference with problem computer is that the problem computer is under Windows 7. But the KeePass itself is working, so... 🤷

**Comment by iav** [comment]
My KeePass 2.56 works with YAFD 1.2.5 correct.
